In [1]:
print("""
@File         : ch02.ipynb
@Author(s)    : Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime  : 2024-06-03 12:39:24
@Email        : cuixuanstephen@gmail.com
@Description  : NumPy 和 Pandas
""")


@File         : ch02.ipynb
@Author(s)    : Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime  : 2024-06-03 12:39:24
@Email        : cuixuanstephen@gmail.com
@Description  : NumPy 和 Pandas



## 理解 NumPy 数组

In [2]:
import numpy as np

In [3]:
a = np.array([2, 4, 6, 8, 10])
print(a)

[ 2  4  6  8 10]


In [5]:
a = np.arange(1, 11)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
p = np.zeros((3, 5))
print(p)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [8]:
q = np.ones((2, 5))
print(q)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
r = np.full((2, 5), 3)
print(r)

[[3 3 3 3 3]
 [3 3 3 3 3]]


In [10]:
s = np.eye(4)
print(s)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
t = np.random.random((3, 5))
print(t)

[[0.82202787 0.19442442 0.77949635 0.28729776 0.39819715]
 [0.02525279 0.83940651 0.46377986 0.92103742 0.44943654]
 [0.11712511 0.64595158 0.52887389 0.36135257 0.02321783]]


### 数组特征

In [13]:
a = np.arange(1, 11)
print(type(a))
print(a.dtype)

<class 'numpy.ndarray'>
int32


In [14]:
print(a.shape)

(10,)


### 选择数组元素

In [15]:
a = np.array([[5, 6], [7, 8]])
print(a)

[[5 6]
 [7 8]]


In [16]:
print(a[0, 0])

5


In [17]:
print(a[0, 1])

6


In [18]:
print(a[1, 0])

7


In [19]:
print(a[1, 1])

8


## NumPy 数组数值数据类型

In [20]:
print(np.float64(42))

42.0


In [22]:
print(np.int8(21.0))

21


In [24]:
print(np.bool_(21))

True


In [25]:
print(np.bool_(0))

False


In [26]:
print(np.bool_(21.0))

True


In [28]:
print(np.float64(True))

1.0


In [29]:
print(np.float64(False))

0.0


In [30]:
np.int(42.0 + 1.j)

C:\Users\JPL-JUNO\AppData\Local\Temp\ipykernel_2600\3633440901.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.int(42.0 + 1.j)


TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'

In [32]:
c = complex(42, 1)
print(c)

(42+1j)


In [33]:
print(c.real, c.imag)

42.0 1.0


### `dtype` 对象

In [34]:
a = np.array([0, 2, 4, 6, 8, 19])
print(a.dtype)

int32


In [38]:
type(a.dtype)

numpy.dtype[int32]

In [39]:
a.dtype.itemsize

4

## 数据类型字符代码

In [40]:
var1 = np.arange(1, 11, dtype='f')
print(var1)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [41]:
print(np.arange(1, 6, dtype='D'))

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j]


### `dtype` 构造函数

In [42]:
print(np.dtype(float))

float64


In [43]:
print(np.dtype('f'))

float32


In [44]:
print(np.dtype('d'))

float64


In [45]:
print(np.dtype('f8'))

float64


### `dtype` 属性

In [47]:
var2 = np.array([1, 2, 3], dtype='float64')
print(var2.dtype.char)

d


In [48]:
print(var2.dtype.type)

<class 'numpy.float64'>


## 操作数组形状

In [49]:
arr = np.arange(12)

In [50]:
new_arr = arr.reshape(4, 3)
new_arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [51]:
arr.reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
arr = np.arange(1, 10).reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
arr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [62]:
arr.resize(1, 9)
arr

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

## NumPy 数组的堆叠

In [64]:
arr1 = np.arange(1, 10).reshape(3, 3)
arr2 = 2 * arr1

In [67]:
arr3 = np.hstack([arr1, arr2])
arr3

array([[ 1,  2,  3,  2,  4,  6],
       [ 4,  5,  6,  8, 10, 12],
       [ 7,  8,  9, 14, 16, 18]])