# The Basics of NumPy Arrays

In [51]:
import numpy as np
rng = np.random.default_rng(seed=1701)

x1 = rng.integers(10, size=6)
x2 = rng.integers(10, size=(3, 4))
x3 = rng.integers(10, size=(3, 4, 5))

## NumPy Array Attributes

In [52]:
print('x3 ndim: ', x3.ndim)
print('x3 shape: ', x3.shape)
print('x3 size: ', x3.size)
print('x3 dtype: ', x3.dtype)

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
x3 dtype:  int64


## Array Indexing: Accessing Single Elements

In [53]:
x1

array([9, 4, 0, 3, 8, 6], dtype=int64)

In [54]:
x1[0], x1[4], x1[-1], x1[-2]

(9, 8, 6, 8)

In [55]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]], dtype=int64)

In [56]:
x2[0, 0], x2[2, 0], x2[2, -1]

(3, 0, 9)

In [57]:
x2[0, 0] = 12
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

In [58]:
x1[0] = 3.14159
x1

array([3, 4, 0, 3, 8, 6], dtype=int64)

## Array Slicing: Accessing Subarrays

### One-Dimensional Subarrays

In [59]:
x1

array([3, 4, 0, 3, 8, 6], dtype=int64)

In [60]:
x1[:3], x1[3:], x1[1:4], x1[::2], x1[1::2]

(array([3, 4, 0], dtype=int64),
 array([3, 8, 6], dtype=int64),
 array([4, 0, 3], dtype=int64),
 array([3, 0, 8], dtype=int64),
 array([4, 3, 6], dtype=int64))

In [61]:
x1[::-1], x1[4::-2]

(array([6, 8, 3, 0, 4, 3], dtype=int64), array([8, 0, 3], dtype=int64))

### Multidimensional Subarrays

In [62]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

In [63]:
x2[:2, :3], x2[:3, ::2], x2[::-1, ::-1]

(array([[12,  1,  3],
        [ 4,  0,  2]], dtype=int64),
 array([[12,  3],
        [ 4,  2],
        [ 0,  6]], dtype=int64),
 array([[ 9,  6,  0,  0],
        [ 3,  2,  0,  4],
        [ 7,  3,  1, 12]], dtype=int64))

In [64]:
x2[:, 0], x2[0, :]

(array([12,  4,  0], dtype=int64), array([12,  1,  3,  7], dtype=int64))

In [65]:
x2[0]

array([12,  1,  3,  7], dtype=int64)

### Subarrays as No-Copy Views

In [66]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

In [67]:
x2_sub = x2[:2, :2]
x2_sub

array([[12,  1],
       [ 4,  0]], dtype=int64)

In [68]:
x2_sub[0, 0] = 99
x2_sub, x2

(array([[99,  1],
        [ 4,  0]], dtype=int64),
 array([[99,  1,  3,  7],
        [ 4,  0,  2,  3],
        [ 0,  0,  6,  9]], dtype=int64))

### Creating Copies of Arrays

## Reshaping of Arrays

In [69]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [70]:
x = np.array([1, 2, 3])
x.reshape((1, 3))

array([[1, 2, 3]])

In [71]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [72]:
x[np.newaxis, :]

array([[1, 2, 3]])

In [73]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting

### Concatenation of Arrays

In [74]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [75]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [76]:
z = np.array([99, 99, 99])
np.concatenate([x, y, z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [77]:
grid = np.array([[1, 2, 3], 
                 [4, 5, 6]])
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [78]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [79]:
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [80]:
y = np.array([[99], 
              [99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

### Splitting of Arrays

In [81]:
x = [1, 2, 3, 99, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [99  3  2  1]


In [82]:
grid = np.arange(16).reshape(4, 4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [83]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [87]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
