In [2]:
import numpy as np
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

data = np.zeros(4, dtype={'names': ('name', 'age', 'weight'),
                          'formats': ('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [4]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [5]:
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [6]:
data[0]

('Alice', 25, 55.)

In [7]:
data['name'][-1]

'Doug'

In [8]:
data[-1]['name']

'Doug'

## Exploring Structured Array Creation

In [9]:
np.dtype({'names': ('name', 'age', 'weight'),
          'formats': ('U10', 'i4', 'f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [10]:
np.dtype({'names': ('name', 'age', 'weight'),
          'formats': ((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [11]:
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

In [12]:
np.dtype('S10, i4, f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

## More Advanced Compound Types

In [16]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Record Arrays: Structured Arrays with a Twist

In [17]:
data['age']

array([25, 45, 37, 19])

In [19]:
data_rec = data.view(np.recarray)
data_rec.age

array([25, 45, 37, 19])

In [20]:
%timeit data['age']

104 ns ± 15.3 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [21]:
%timeit data_rec.age

2.93 µs ± 257 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [22]:
%timeit data_rec['age']

1.51 µs ± 87 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
